
""" Example
    GKY_KEHOACHDANGKY_ID: "F6C1A50758B34DBA9EC0115D6F99FF50"
    DANGKY_LOPHOCPHAN_ID: "B0E5BE5F452B48DA92BD9444EE8BB659"
    DANGKY_LOPHOCPHAN_MA: "IE3.006.3-1-2-24(QT(TA)01.TH1)"
    DANGKY_LOPHOCPHAN_TEN: "An toàn và bảo mật thông tin-1-2-24(QT(TA)01.TH1)"
    DAOTAO_HOCPHAN_ID: "4C1CED1FFD554665A98951673543E2FC"
    DAOTAO_HOCPHAN_MA: "IE3.006.3"
    DAOTAO_HOCPHAN_TEN: "An toàn và bảo mật thông tin"
    DAOTAO_LOPQUANLY_ID: "2D684749CE694B92B4F22F9755056E4D"
    DAOTAO_LOPQUANLY_MA: "K63.CNTTVA1(QT)"
    DAOTAO_LOPQUANLY_TEN: "CLC Công nghệ thông tin Việt - Anh 1 63"
    DAOTAO_THOIGIANDAOTAO_ID: "B4603D6CA1F64AD2996555352BFE26AC"
    DAOTAO_TOCHUCCHUONGTRINH_ID: "B39110B1BFC643F5AA49A845B55404C5"
    DAOTAO_TOCHUCCHUONGTRINH_MA: "7480201.1QT"
    DAOTAO_TOCHUCCHUONGTRINH_TEN: "CLC Công nghệ thông tin Việt - Anh"
    GIANGVIEN: null
    ID: "E7D640D882FB44E5A3EDBAEA4390737E"
    KHONGKIEMTRATRUNGLICHHOC: null
    KIEUHOC_ID: "6B0AA24EB43A4C67A82D5C015E6267F0"
    KIEUHOC_MA: "HOCDI"
    KIEUHOC_TEN: "Học đi"
    LOPHOCPHANCHINH: 0
    MANHOMLOP: "970AF40FF2B24089A82FB246371F8AEB"
    NGAYBATDAU: "31/03/2025"
    NGAYKETTHUC: "11/05/2025"
    NGAYTAO: "20241217230422"
    NGAYTAO_YYYYMMDDHH24MISSFF3: "20241217230422557"
    NGUOITAO_ID: "d8bcde87f70247b19a1bae88dddd40a0"
    PHISAUKHITRUMIEN: null
    QLSV_NGUOIHOC_HODEM: "Lý Trần"
    QLSV_NGUOIHOC_ID: "d8bcde87f70247b19a1bae88dddd40a0"
    QLSV_NGUOIHOC_MASO: "222631159"
    QLSV_NGUOIHOC_TEN: "Vinh"
    QLSV_TRANGTHAINGUOIHOC_ID: "EB92A6A2570F47AB8498D7C077EF5B7D"
    QLSV_TRANGTHAINGUOIHOC_MA: "NORMAL"
    QLSV_TRANGTHAINGUOIHOC_TEN: "Đang học"
    SOLUONGDUKIENHOC: 48
    SOTHUCTEDANGKYHOC: 48
    SOTINCHIDADANGKY: 22
    TEMP_DANGKY_LOPHOCPHAN_IDS: null
    TEMP_KIEMTRASOTINCHITOIDA: 0
    TEMP_KIEMTRATAICHINH: 0
    TEMP_KIEMTRATRUNGLICH: 1
    TEMP_KIEMTRATRUNGLOPKHONGXEP: 0
    TEMP_KIEMTRATRUNGTHOIGIAN_ID: "EA25B37003F747EFBFD32C272F594E8B"
    TEMP_KIEUHOC_IDS: "991314249B7E4DE1BFBAA3882E1FFBF6,6B0AA24EB43A4C67A82D5C015E6267F0,9D5E348ADA8F47BF9EC628436D8138BB"
    TEMP_NO_CO: 0
    TEMP_PHANTRAMDANGKYVUOTQUYDINH: 0
    TEMP_PHIDUOCMIEN: 0
    TEMP_PHIPHAIDONG: 0
    TEMP_QUYDINHKIEMTRAHOCPHI_ID: null
    TEMP_QUYDINHTINCHITOIDA_ID: "25F8A73430734DA99B4FA5FE6727E6A8"
    TEMP_SOHOCPHINOTOIDACHOPHEP: 0
    TEMP_SOTINCHITOIDA: 0
    THUHOC: null
    THUHOC_TIETHOC: null
    THUOCTINHLOP_ID: "4094e40f71fc4f129db637ebb508e5a2"
    THUOCTINHLOP_TEN: "Thực hành"
"""

class lop_hoc_phan:
    def __init__(self, **args):
        self.GKY_KEHOACHDANGKY_ID = args.set('GKY_KEHOACHDANGKY_ID')
        self.DANGKY_LOPHOCPHAN_ID = args.set('DANGKY_LOPHOCPHAN_ID')
        self.DANGKY_LOPHOCPHAN_MA = args.set('DANGKY_LOPHOCPHAN_MA')
        self.DANGKY_LOPHOCPHAN_TEN = args.set('DANGKY_LOPHOCPHAN_TEN')
        self.DAOTAO_HOCPHAN_ID = args.set('DAOTAO_HOCPHAN_ID')
        self.DAOTAO_HOCPHAN_MA = args.set('DAOTAO_HOCPHAN_MA')
        self.DAOTAO_HOCPHAN_TEN = args.set('DAOTAO_HOCPHAN_TEN')
        self.DAOTAO_LOPQUANLY_ID = args.set('DAOTAO_LOPQUANLY_ID')
        self.DAOTAO_LOPQUANLY_MA = args.set('DAOTAO_LOPQUANLY_MA')
        self.DAOTAO_LOPQUANLY_TEN = args.set('DAOTAO_LOPQUANLY_TEN')
        self.DAOTAO_THOIGIANDAOTAO_ID = args.set('DAOTAO_THOIGIANDAOTAO_ID')
        self.DAOTAO_TOCHUCCHUONGTRINH_ID = args.set('DAOTAO_TOCHUCCHUONGTRINH_ID')
        self.DAOTAO_TOCHUCCHUONGTRINH_MA = args.set('DAOTAO_TOCHUCCHUONGTRINH_MA')
        self.DAOTAO_TOCHUCCHUONGTRINH_TEN = args.set('DAOTAO_TOCHUCCHUONGTRINH_TEN')
        self.GIANGVIEN = args.set('GIANGVIEN', None)
        self.ID = args.set('ID')
        self.KHONGKIEMTRATRUNGLICHHOC = args.set('KHONGKIEMTRATRUNGLICHHOC')
        self.KIEUHOC_ID = args.set('KIEUHOC_ID')
        self.KIEUHOC_MA = args.set('KIEUHOC_MA')
        self.KIEUHOC_TEN = args.set('KIEUHOC_TEN')
        self.LOPHOCPHANCHINH = args.set('LOPHOCPHANCHINH', 0)
        self.MANHOMLOP = args.set('MANHOMLOP')
        self.NGAYBATDAU = args.set('NGAYBATDAU')
        self.NGAYKETTHUC = args.set('NGAYKETTHUC')
        self.NGAYTAO = args.set('NGAYTAO')
        self.NGAYTAO_YYYYMMDDHH24MISSFF3 = args.set('NGAYTAO_YYYYMMDDHH24MISSFF3')
        self.NGUOITAO_ID = args.set('NGUOITAO_ID')
        self.PHISAUKHITRUMIEN = args.set('PHISAUKHITRUMIEN', None)
        self.QLSV_NGUOIHOC_HODEM = args.set('QLSV_NGUOIHOC_HODEM')
        self.QLSV_NGUOIHOC_ID = args.set('QLSV_NGUOIHOC_ID')
        self.QLSV_NGUOIHOC_MASO = args.set('QLSV_NGUOIHOC_MASO')
        self.QLSV_NGUOIHOC_TEN = args.set('QLSV_NGUOIHOC_TEN')
        self.QLSV_TRANGTHAINGUOIHOC_ID = args.set('QLSV_TRANGTHAINGUOIHOC_ID')
        self.QLSV_TRANGTHAINGUOIHOC_MA = args.set('QLSV_TRANGTHAINGUOIHOC_MA')
        self.QLSV_TRANGTHAINGUOIHOC_TEN = args.set('QLSV_TRANGTHAINGUOIHOC_TEN')
        self.SOLUONGDUKIENHOC = args.set('SOLUONGDUKIENHOC')
        self.SOTHUCTEDANGKYHOC = args.set('SOTHUCTEDANGKYHOC')
        self.SOTINCHIDADANGKY = args.set('SOTINCHIDADANGKY')
        self.TEMP_DANGKY_LOPHOCPHAN_IDS = args.set('TEMP_DANGKY_LOPHOCPHAN_IDS')
        self.TEMP_KIEMTRASOTINCHITOIDA = args.set('TEMP_KIEMTRASOTINCHITOIDA')
        self.TEMP_KIEMTRATAICHINH = args.set('TEMP_KIEMTRATAICHINH')
        self.TEMP_KIEMTRATRUNGLICH = args.set('TEMP_KIEMTRATRUNGLICH')
        self.TEMP_KIEMTRATRUNGLOPKHONGXEP = args.set('TEMP_KIEMTRATRUNGLOPKHONGXEP')
        self.TEMP_KIEMTRATRUNGTHOIGIAN_ID = args.set('TEMP_KIEMTRATRUNGTHOIGIAN_ID')
        self.TEMP_KIEUHOC_IDS = args.set('TEMP_KIEUHOC_IDS')
        self.TEMP_NO_CO = args.set('TEMP_NO_CO')
        self.TEMP_PHANTRAMDANGKYVUOTQUYDINH = args.set('TEMP_PHANTRAMDANGKYVUOTQUYDINH')
        self.TEMP_PHIDUOCMIEN = args.set('TEMP_PHIDUOCMIEN')
        self.TEMP_PHIPHAIDONG = args.set('TEMP_PHIPHAIDONG')
        self.TEMP_QUYDINHKIEMTRAHOCPHI_ID = args.set('TEMP_QUYDINHKIEMTRAHOCPHI_ID')
        self.TEMP_QUYDINHTINCHITOIDA_ID = args.set('TEMP_QUYDINHTINCHITOIDA_ID')
        self.TEMP_SOHOCPHINOTOIDACHOPHEP = args.set('TEMP_SOHOCPHINOTOIDACHOPHEP')
        self.TEMP_SOTINCHITOIDA = args.set('TEMP_SOTINCHITOIDA')
        self.THUHOC = args.set('THUHOC')
        self.THUHOC_TIETHOC = args.set('THUHOC_TIETHOC')
        self.THUOCTINHLOP_ID = args.set('THUOCTINHLOP_ID')
        self.THUOCTINHLOP_TEN = args.set('THUOCTINHLOP_TEN')
    