
""" Example
    GKY_KEHOACHDANGKY_ID: "F6C1A50758B34DBA9EC0115D6F99FF50"
    DANGKY_LOPHOCPHAN_ID: "B0E5BE5F452B48DA92BD9444EE8BB659"
    DANGKY_LOPHOCPHAN_MA: "IE3.006.3-1-2-24(QT(TA)01.TH1)"
    DANGKY_LOPHOCPHAN_TEN: "An toàn và bảo mật thông tin-1-2-24(QT(TA)01.TH1)"
    DAOTAO_HOCPHAN_ID: "4C1CED1FFD554665A98951673543E2FC"
    DAOTAO_HOCPHAN_MA: "IE3.006.3"
    DAOTAO_HOCPHAN_TEN: "An toàn và bảo mật thông tin"
    DAOTAO_LOPQUANLY_ID: "2D684749CE694B92B4F22F9755056E4D"
    DAOTAO_LOPQUANLY_MA: "K63.CNTTVA1(QT)"
    DAOTAO_LOPQUANLY_TEN: "CLC Công nghệ thông tin Việt - Anh 1 63"
    DAOTAO_THOIGIANDAOTAO_ID: "B4603D6CA1F64AD2996555352BFE26AC"
    DAOTAO_TOCHUCCHUONGTRINH_ID: "B39110B1BFC643F5AA49A845B55404C5"
    DAOTAO_TOCHUCCHUONGTRINH_MA: "7480201.1QT"
    DAOTAO_TOCHUCCHUONGTRINH_TEN: "CLC Công nghệ thông tin Việt - Anh"
    GIANGVIEN: null
    ID: "E7D640D882FB44E5A3EDBAEA4390737E"
    KHONGKIEMTRATRUNGLICHHOC: null
    KIEUHOC_ID: "6B0AA24EB43A4C67A82D5C015E6267F0"
    KIEUHOC_MA: "HOCDI"
    KIEUHOC_TEN: "Học đi"
    LOPHOCPHANCHINH: 0
    MANHOMLOP: "970AF40FF2B24089A82FB246371F8AEB"
    NGAYBATDAU: "31/03/2025"
    NGAYKETTHUC: "11/05/2025"
    NGAYTAO: "20241217230422"
    NGAYTAO_YYYYMMDDHH24MISSFF3: "20241217230422557"
    NGUOITAO_ID: "d8bcde87f70247b19a1bae88dddd40a0"
    PHISAUKHITRUMIEN: null
    QLSV_NGUOIHOC_HODEM: "Lý Trần"
    QLSV_NGUOIHOC_ID: "d8bcde87f70247b19a1bae88dddd40a0"
    QLSV_NGUOIHOC_MASO: "222631159"
    QLSV_NGUOIHOC_TEN: "Vinh"
    QLSV_TRANGTHAINGUOIHOC_ID: "EB92A6A2570F47AB8498D7C077EF5B7D"
    QLSV_TRANGTHAINGUOIHOC_MA: "NORMAL"
    QLSV_TRANGTHAINGUOIHOC_TEN: "Đang học"
    SOLUONGDUKIENHOC: 48
    SOTHUCTEDANGKYHOC: 48
    SOTINCHIDADANGKY: 22
    TEMP_DANGKY_LOPHOCPHAN_IDS: null
    TEMP_KIEMTRASOTINCHITOIDA: 0
    TEMP_KIEMTRATAICHINH: 0
    TEMP_KIEMTRATRUNGLICH: 1
    TEMP_KIEMTRATRUNGLOPKHONGXEP: 0
    TEMP_KIEMTRATRUNGTHOIGIAN_ID: "EA25B37003F747EFBFD32C272F594E8B"
    TEMP_KIEUHOC_IDS: "991314249B7E4DE1BFBAA3882E1FFBF6,6B0AA24EB43A4C67A82D5C015E6267F0,9D5E348ADA8F47BF9EC628436D8138BB"
    TEMP_NO_CO: 0
    TEMP_PHANTRAMDANGKYVUOTQUYDINH: 0
    TEMP_PHIDUOCMIEN: 0
    TEMP_PHIPHAIDONG: 0
    TEMP_QUYDINHKIEMTRAHOCPHI_ID: null
    TEMP_QUYDINHTINCHITOIDA_ID: "25F8A73430734DA99B4FA5FE6727E6A8"
    TEMP_SOHOCPHINOTOIDACHOPHEP: 0
    TEMP_SOTINCHITOIDA: 0
    THUHOC: null
    THUHOC_TIETHOC: null
    THUOCTINHLOP_ID: "4094e40f71fc4f129db637ebb508e5a2"
    THUOCTINHLOP_TEN: "Thực hành"
"""

class lop_hoc_phan:
    def __init__(self, **args):
        self.GKY_KEHOACHDANGKY_ID = args.get('GKY_KEHOACHDANGKY_ID', None)
        self.DANGKY_LOPHOCPHAN_ID = args.get('DANGKY_LOPHOCPHAN_ID', None)
        self.DANGKY_LOPHOCPHAN_MA = args.get('DANGKY_LOPHOCPHAN_MA', None)
        self.DANGKY_LOPHOCPHAN_TEN = args.get('DANGKY_LOPHOCPHAN_TEN', None)
        self.DAOTAO_HOCPHAN_ID = args.get('DAOTAO_HOCPHAN_ID', None)
        self.DAOTAO_HOCPHAN_MA = args.get('DAOTAO_HOCPHAN_MA', None)
        self.DAOTAO_HOCPHAN_TEN = args.get('DAOTAO_HOCPHAN_TEN', None)
        self.DAOTAO_LOPQUANLY_ID = args.get('DAOTAO_LOPQUANLY_ID', None)
        self.DAOTAO_LOPQUANLY_MA = args.get('DAOTAO_LOPQUANLY_MA', None)
        self.DAOTAO_LOPQUANLY_TEN = args.get('DAOTAO_LOPQUANLY_TEN', None)
        self.DAOTAO_THOIGIANDAOTAO_ID = args.get('DAOTAO_THOIGIANDAOTAO_ID', None)
        self.DAOTAO_TOCHUCCHUONGTRINH_ID = args.get('DAOTAO_TOCHUCCHUONGTRINH_ID', None)
        self.DAOTAO_TOCHUCCHUONGTRINH_MA = args.get('DAOTAO_TOCHUCCHUONGTRINH_MA', None)
        self.DAOTAO_TOCHUCCHUONGTRINH_TEN = args.get('DAOTAO_TOCHUCCHUONGTRINH_TEN', None)
        self.GIANGVIEN = args.get('GIANGVIEN', None)
        self.ID = args.get('ID', None)
        self.KHONGKIEMTRATRUNGLICHHOC = args.get('KHONGKIEMTRATRUNGLICHHOC', None)
        self.KIEUHOC_ID = args.get('KIEUHOC_ID', None)
        self.KIEUHOC_MA = args.get('KIEUHOC_MA', None)
        self.KIEUHOC_TEN = args.get('KIEUHOC_TEN', None)
        self.LOPHOCPHANCHINH = args.get('LOPHOCPHANCHINH', 0)
        self.MANHOMLOP = args.get('MANHOMLOP', None)
        self.NGAYBATDAU = args.get('NGAYBATDAU', None)
        self.NGAYKETTHUC = args.get('NGAYKETTHUC', None)
        self.NGAYTAO = args.get('NGAYTAO', None)
        self.NGAYTAO_YYYYMMDDHH24MISSFF3 = args.get('NGAYTAO_YYYYMMDDHH24MISSFF3', None)
        self.NGUOITAO_ID = args.get('NGUOITAO_ID', None)
        self.PHISAUKHITRUMIEN = args.get('PHISAUKHITRUMIEN', None)
        self.QLSV_NGUOIHOC_HODEM = args.get('QLSV_NGUOIHOC_HODEM', None)
        self.QLSV_NGUOIHOC_ID = args.get('QLSV_NGUOIHOC_ID', None)
        self.QLSV_NGUOIHOC_MASO = args.get('QLSV_NGUOIHOC_MASO', None)
        self.QLSV_NGUOIHOC_TEN = args.get('QLSV_NGUOIHOC_TEN', None)
        self.QLSV_TRANGTHAINGUOIHOC_ID = args.get('QLSV_TRANGTHAINGUOIHOC_ID', None)
        self.QLSV_TRANGTHAINGUOIHOC_MA = args.get('QLSV_TRANGTHAINGUOIHOC_MA', None)
        self.QLSV_TRANGTHAINGUOIHOC_TEN = args.get('QLSV_TRANGTHAINGUOIHOC_TEN', None)
        self.SOLUONGDUKIENHOC = args.get('SOLUONGDUKIENHOC', None)
        self.SOTHUCTEDANGKYHOC = args.get('SOTHUCTEDANGKYHOC', None)
        self.SOTINCHIDADANGKY = args.get('SOTINCHIDADANGKY', None)
        self.TEMP_DANGKY_LOPHOCPHAN_IDS = args.get('TEMP_DANGKY_LOPHOCPHAN_IDS', None)
        self.TEMP_KIEMTRASOTINCHITOIDA = args.get('TEMP_KIEMTRASOTINCHITOIDA', None)
        self.TEMP_KIEMTRATAICHINH = args.get('TEMP_KIEMTRATAICHINH', None)
        self.TEMP_KIEMTRATRUNGLICH = args.get('TEMP_KIEMTRATRUNGLICH', None)
        self.TEMP_KIEMTRATRUNGLOPKHONGXEP = args.get('TEMP_KIEMTRATRUNGLOPKHONGXEP', None)
        self.TEMP_KIEMTRATRUNGTHOIGIAN_ID = args.get('TEMP_KIEMTRATRUNGTHOIGIAN_ID', None)
        self.TEMP_KIEUHOC_IDS = args.get('TEMP_KIEUHOC_IDS', None)
        self.TEMP_NO_CO = args.get('TEMP_NO_CO', None)
        self.TEMP_PHANTRAMDANGKYVUOTQUYDINH = args.get('TEMP_PHANTRAMDANGKYVUOTQUYDINH', None)
        self.TEMP_PHIDUOCMIEN = args.get('TEMP_PHIDUOCMIEN', None)
        self.TEMP_PHIPHAIDONG = args.get('TEMP_PHIPHAIDONG', None)
        self.TEMP_QUYDINHKIEMTRAHOCPHI_ID = args.get('TEMP_QUYDINHKIEMTRAHOCPHI_ID', None)
        self.TEMP_QUYDINHTINCHITOIDA_ID = args.get('TEMP_QUYDINHTINCHITOIDA_ID', None)
        self.TEMP_SOHOCPHINOTOIDACHOPHEP = args.get('TEMP_SOHOCPHINOTOIDACHOPHEP', None)
        self.TEMP_SOTINCHITOIDA = args.get('TEMP_SOTINCHITOIDA', None)
        self.THUHOC = args.get('THUHOC', None)
        self.THUHOC_TIETHOC = args.get('THUHOC_TIETHOC', None)
        self.THUOCTINHLOP_ID = args.get('THUOCTINHLOP_ID', None)
        self.THUOCTINHLOP_TEN = args.get('THUOCTINHLOP_TEN', None)
    
    def toJson(self):
        return {
            "GKY_KEHOACHDANGKY_ID": self.GKY_KEHOACHDANGKY_ID,
            "DANGKY_LOPHOCPHAN_ID": self.DANGKY_LOPHOCPHAN_ID,
            "DANGKY_LOPHOCPHAN_MA": self.DANGKY_LOPHOCPHAN_MA,
            "DANGKY_LOPHOCPHAN_TEN": self.DANGKY_LOPHOCPHAN_TEN,
            "DAOTAO_HOCPHAN_ID": self.DAOTAO_HOCPHAN_ID,
            "DAOTAO_HOCPHAN_MA": self.DAOTAO_HOCPHAN_MA,
            "DAOTAO_HOCPHAN_TEN": self.DAOTAO_HOCPHAN_TEN,
            "DAOTAO_LOPQUANLY_ID": self.DAOTAO_LOPQUANLY_ID,
            "DAOTAO_LOPQUANLY_MA": self.DAOTAO_LOPQUANLY_MA,
            "DAOTAO_LOPQUANLY_TEN": self.DAOTAO_LOPQUANLY_TEN,
            "DAOTAO_THOIGIANDAOTAO_ID": self.DAOTAO_THOIGIANDAOTAO_ID,
            "DAOTAO_TOCHUCCHUONGTRINH_ID": self.DAOTAO_TOCHUCCHUONGTRINH_ID,
            "DAOTAO_TOCHUCCHUONGTRINH_MA": self.DAOTAO_TOCHUCCHUONGTRINH_MA,
            "DAOTAO_TOCHUCCHUONGTRINH_TEN": self.DAOTAO_TOCHUCCHUONGTRINH_TEN,
            "GIANGVIEN": self.GIANGVIEN,
            "ID": self.ID,
            "KHONGKIEMTRATRUNGLICHHOC": self.KHONGKIEMTRATRUNGLICHHOC,
            "KIEUHOC_ID": self.KIEUHOC_ID,
            "KIEUHOC_MA": self.KIEUHOC_MA,
            "KIEUHOC_TEN": self.KIEUHOC_TEN,
            "LOPHOCPHANCHINH": self.LOPHOCPHANCHINH,
            "MANHOMLOP": self.MANHOMLOP,
            "NGAYBATDAU": self.NGAYBATDAU,
            "NGAYKETTHUC": self.NGAYKETTHUC,
            "NGAYTAO": self.NGAYTAO,
            "NGAYTAO_YYYYMMDDHH24MISSFF3": self.NGAYTAO_YYYYMMDDHH24MISSFF3,
            "NGUOITAO_ID": self.NGUOITAO_ID,
            "PHISAUKHITRUMIEN": self.PHISAUKHITRUMIEN,
            "QLSV_NGUOIHOC_HODEM": self.QLSV_NGUOIHOC_HODEM,
            "QLSV_NGUOIHOC_ID": self.QLSV_NGUOIHOC_ID,
            "QLSV_NGUOIHOC_MASO": self.QLSV_NGUOIHOC_MASO,
            "QLSV_NGUOIHOC_TEN": self.QLSV_NGUOIHOC_TEN,
            "QLSV_TRANGTHAINGUOIHOC_ID": self.QLSV_TRANGTHAINGUOIHOC_ID,
            "QLSV_TRANGTHAINGUOIHOC_MA": self.QLSV_TRANGTHAINGUOIHOC_MA,
            "QLSV_TRANGTHAINGUOIHOC_TEN": self.QLSV_TRANGTHAINGUOIHOC_TEN,
            "SOLUONGDUKIENHOC": self.SOLUONGDUKIENHOC,
            "SOTHUCTEDANGKYHOC": self.SOTHUCTEDANGKYHOC,
            "SOTINCHIDADANGKY": self.SOTINCHIDADANGKY,
            "TEMP_DANGKY_LOPHOCPHAN_IDS": self.TEMP_DANGKY_LOPHOCPHAN_IDS,
            "TEMP_KIEMTRASOTINCHITOIDA": self.TEMP_KIEMTRASOTINCHITOIDA,
            "TEMP_KIEMTRATAICHINH": self.TEMP_KIEMTRATAICHINH,
            "TEMP_KIEMTRATRUNGLICH": self.TEMP_KIEMTRATRUNGLICH,
            "TEMP_KIEMTRATRUNGLOPKHONGXEP": self.TEMP_KIEMTRATRUNGLOPKHONGXEP,
            "TEMP_KIEMTRATRUNGTHOIGIAN_ID": self.TEMP_KIEMTRATRUNGTHOIGIAN_ID,
            "TEMP_KIEUHOC_IDS": self.TEMP_KIEUHOC_IDS,
            "TEMP_NO_CO": self.TEMP_NO_CO,
            "TEMP_PHANTRAMDANGKYVUOTQUYDINH": self.TEMP_PHANTRAMDANGKYVUOTQUYDINH,
            "TEMP_PHIDUOCMIEN": self.TEMP_PHIDUOCMIEN,
            "TEMP_PHIPHAIDONG": self.TEMP_PHIPHAIDONG,
            "TEMP_QUYDINHKIEMTRAHOCPHI_ID": self.TEMP_QUYDINHKIEMTRAHOCPHI_ID,
            "TEMP_QUYDINHTINCHITOIDA_ID": self.TEMP_QUYDINHTINCHITOIDA_ID,
            "TEMP_SOHOCPHINOTOIDACHOPHEP": self.TEMP_SOHOCPHINOTOIDACHOPHEP,
            "TEMP_SOTINCHITOIDA": self.TEMP_SOTINCHITOIDA,
            "THUHOC": self.THUHOC,
            "THUHOC_TIETHOC": self.THUHOC_TIETHOC,
            "THUOCTINHLOP_ID": self.THUOCTINHLOP_ID,
            "THUOCTINHLOP_TEN": self.THUOCTINHLOP_TEN,
        }